model:
  name: 'shuffleNetLight'
  pretrained: False
  resume: ../model.pth.tar-100

data:
  type: 'image'
  sources: ['dukemtmcreid']
  targets: ['dukemtmcreid']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_crop', 'random_patch']
  save_dir: 'log/duke/shufflenet'

cuhk03: 
  use_metric_cuhk03: False

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'sgd'
  lr: 0.065
  max_epoch: 350
  batch_size: 32
  fixbase_epoch: 0
  lr_scheduler: multi_step
  stepsize: [150, 225, 300]

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: 50
  rerank: False